name: Deploy to Windows VPS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy na VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: powershell -Command "cd 'C:\sampa-concept'; git pull; npm install --omit=dev; npm run build; pm2 restart sampa-concept --update-env; if ($LASTEXITCODE -ne 0) { pm2 start npm --name 'sampa-concept' -- start; pm2 save }"